#!C:\Users\troyk\OneDrive\Desktop\212_Umbral_Observer\212-umob\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
